server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
