spring:
  application:
    name: user-service
server:
  port: 9001
springdoc:
  swagger-ui:
    operationsSorter: method

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
