spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Personal/Learn/Spring/spring-playground/microservices/config-repository
          default-label: master

  application:
    name: config-service

server:
  port: 8888